name: Development tests
on:
  push:
    branches:
      - development
    paths:
      - .github/workflows/development.yaml
      - src/**
      - tests/**
      - config.py
      - main.py
jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install ruff
        run: pip install ruff
      - name: Linting
        run: ruff check .
      - name: Formatting
        run: ruff format . --check
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Checking
        run: pyright .
  tests:
    runs-on: ubuntu-latest
    needs:
      - code-quality
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Testing
        run: pytest -v --durations=0 --cov --cov-report=xml
      - name: Codecov push
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}